plugins {
    id("com.android.library")
    id("kotlin-android")
}

version '1.0'

def onfidoSdkVersion = '22.5.+'


rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

android {
    compileSdkVersion 34
    namespace 'com.onfido.sdk.flutter'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        minSdkVersion 21
    }
}

dependencies {
    implementation "com.onfido.sdk.capture:onfido-capture-sdk:$onfidoSdkVersion"
    implementation "com.onfido.sdk:onfido-workflow:$onfidoSdkVersion"
}
